### ISSUE TITLE
Audit: Use memory instead of storage

### ISSUE THREAD

**Issue by 0x3agle** [Steemhunt/mint.club-v2-contract#10]
I think `memory` should be used instead of `storage` on the following [line]( https://github.com/Steemhunt/mint.club-v2-contract/blob/main/contracts/MCV2_Bond.sol#L339). The comment mentions the same

This code block
```solidity
Bond storage bond = tokenBond[token];
// Store bond.steps in memory to minimize sloads
BondStep[] storage steps = bond.steps;
```
Could be refactored to:
```solidity
BondStep[] memory steps = tokenBond[token].steps;
```

**Comment by ddimitrov22** [comment]
Agree here. There is a discrepancy between the code and the comment.

**Comment by sydneyitguy** [comment]
Good catch! I just fixed it. Thanks :)
