### ISSUE TITLE
Audit : Simplify code 

### ISSUE THREAD

**Issue by byeonggoon** [Steemhunt/mint.club-v2-contract#19]
In the createDistribution function in MerkleDistributor.sol

![image](https://github.com/Steemhunt/mint.club-v2-contract/assets/77770252/357b6168-161c-4bd5-8a49-f57847082656)

There is this part

![image](https://github.com/Steemhunt/mint.club-v2-contract/assets/77770252/975a899a-0ee4-4a2b-aa46-d836df3a5b1e)

How about modifying it like this?

**Comment by exd0tpy** [comment]
I think that the current implementation is effective in reducing gas costs

**Comment by sydneyitguy** [comment]
It's not possible because a struct containing a nested mapping cannot be constructed.
