### ISSUE TITLE
Audit: distribution Claimed check 

### ISSUE THREAD

**Issue by byeonggoon** [Steemhunt/mint.club-v2-contract#20]
If you look at the claim function in MerkleDistributor.sol,
<img width="1139" alt="스크린샷 2023-12-09 오후 4 18 19" src="https://github.com/Steemhunt/mint.club-v2-contract/assets/77770252/a738aefb-10db-471a-bf93-c50db3a917a7">
There is a part like the above.

If distrubution.walletCount is 2, when a claim is made once, isClaimed becomes true, so revert occurs at line 107, so the check at line 108 is useless. And the user will not be able to make more claim.
Therefore, revert using isClaimed does not seem to be necessary here.

**Comment by sydneyitguy** [comment]
```js
if (distribution.isClaimed[msg.sender]) revert MerkleDistributor__AlreadyClaimed();
```
This line checks if msg.sender has already claimed the airdrop.

```js
if (distribution.claimedCount >= distribution.walletCount) revert MerkleDistributor__NoClaimableTokensLeft();
```
This line checks if the total number of claims has reached the maximum wallet count (claimable count) for this distribution. For example, if the airdrop targets 100 users (wallet count) and 100 users have already claimed the airdrop, it will revert at this line.

**Comment by byeonggoon** [comment]
Yes, that's right, I misunderstood.
thank you for telling me. !
