### ISSUE TITLE
NatSpec docs are incomplete

### ISSUE THREAD

**Issue by madMax92221** [Steemhunt/mint.club-v2-contract#24]
All external methods are missing NatSpec documentation which is essential for better understanding of the code by developers and auditors and is strongly recommended. 

Please refer to the [NatSpec format](https://docs.soliditylang.org/en/v0.8.17/natspec-format.html) and follow the guidelines outlined there.

**Comment by sydneyitguy** [comment]
Thanks for pointing this out!
I just updated the code, adding comments with NatSpec format :)
