### ISSUE TITLE
Unused code can be removed from the contracts

### ISSUE THREAD

**Issue by madMax92221** [Steemhunt/mint.club-v2-contract#26]
There are 4 instances where certain variables/ custom errors are declared but not used anywhere in the codebase.

Consider either using them or removing them from the contracts:

- `MINT_CONTRACT` variable in `MCV1_Wrapper.sol`

-  `MCV2_Bond__InvalidRefundAmount` error in `MCV2_Bond.sol`

- `MCV2_Royalty__TokenTransferFailed` error in `MCV2_Royalty.sol`

- `MerkleDistributor__NoRefundDuringClaim` error in `MerkleDistributor.sol`

**Comment by sydneyitguy** [comment]
Thanks for pointing this out!

The `MINT_CONTRACT` variable in `MCV1_Wrapper.sol` was for the informational view function purpose on the front-end.
