### ISSUE TITLE
Single-step ownership transfer pattern is dangerous

### ISSUE THREAD

**Issue by madMax92221** [Steemhunt/mint.club-v2-contract#27]
We can observe the inheritance of `Ownable` in `MCV2_Royalty.sol`. Inheriting from OpenZeppelin's `Ownable` contract means you are using a single-step ownership transfer pattern. 

If an admin provides an incorrect address for the new owner this will result in none of the `onlyOwner` marked methods being callable again. 

The better way to do this is to use a two-step ownership transfer approach, where the new owner should first claim its new rights before they are transferred. Use OpenZeppelin's `Ownable2Step` instead of `Ownable`.

**Comment by the-first-elder** [comment]
I strongly suggest this should be considered as well

**Comment by sydneyitguy** [comment]
Thanks for your suggestion, but the admin function is not really critical and won't be called frequently, if at all, because it only has one owner function, which is changing the protocol beneficiary address. I will keep this implementation as simple as it is now.
