### ISSUE TITLE
Bytecode might not be compatible with all EVM-based chains

### ISSUE THREAD

**Issue by madMax92221** [Steemhunt/mint.club-v2-contract#29]
The `pragma` statement in each contract shows usage of  floatable 0.8.20 version of the Solidity compiler. This version (and every version after 0.8.19) will use the `PUSH0` opcode, which is still not supported on some EVM-based chains, for example Arbitrum.  If the protocol is expected to be deployed on multiple EVM-based chains (Optimism, Arbitrum, Polygon etc), that will be problematic.

Consider using version 0.8.19 so that the same deterministic bytecode can be deployed to all chains.

Even if the protocol is not expected to be deployed on multiple EVM-based chains, always use stable pragma statement to lock the compiler version and to have deterministic compilation to bytecode.

```diff
- pragma solidity ^0.8.20;
+ pragma solidity 0.8.19;
```

**Comment by sydneyitguy** [comment]
Oh, I actually deployed this successfully on the Base chain, but haven't tried it with Arbitrum and other chains yet. 

It could be problematic if I have to downgrade to Solidity 0.8.19, because OpenZeppelin 5.0.1 also uses Solidity 0.8.20.
Hmm, downgrading OZ to 4.9.5 is not easy because I've already used custom errors across our contract and test cases.

I guess we could just wait to deploy on those chains until those Layer 2 solutions support PUSH0, right? 🤔

**Comment by madMax92221** [comment]
Yes, thats an option, since the only big problem (as far as the sector knows right now) with Solidity version > 0.8.19 is the PUSH0 opcode. If you wait on the deployment till the chains start to support PUSH0, I believe you will be alright.

**Comment by sydneyitguy** [comment]
Thanks for the clarification!
I will check the schedules made for each L2 chain and decide if we have to downgrade to 0.8.19 or wait for them to upgrade.
I will leave this ticket open until we decide.

Thank you for your contribution! :)

**Comment by web3isthefuture** [comment]
Even I'm also dealing with multi-chain, I didn't know this at all.
Kudos @madMax92221 for letting us know about this.

**Comment by sydneyitguy** [comment]
It seems Hardhat uses `evmVersion: "paris"` when the Solidity version is >= 0.8.20 to address this issue.
Reference: https://hardhat.org/hardhat-runner/docs/config#default-evm-version

One disadvantage of using the "paris" hardfork is higher gas fees on deployments, but this is not a significant issue.
I will close this issue if there are no more feedbacks regarding this.
