### ISSUE TITLE
Using private rather than public for constants, saves gas

### ISSUE THREAD

**Issue by madMax92221** [Steemhunt/mint.club-v2-contract#30]
If needed, the values can be read from the verified contract source code, or if there are multiple values there can be a single getter function that returns a tuple of the values of all currently-public constants. Saves 3406-3606 gas in deployment gas due to the compiler not having to create non-payable getter functions for deployment calldata, not having to store the bytes of the value outside of where it's used, and not adding another entry to the method ID table.

`MCV1_Wrapper.sol`

```solidity
IMintClubBond public constant BOND = IMintClubBond(0x8BBac0C7583Cc146244a18863E708bFFbbF19975); //@audit constants can be private
 address public constant MINT_CONTRACT = address(0x1f3Af095CDa17d63cad238358837321e95FC5915); //@audit constants can be private
 ```

**Comment by the-first-elder** [comment]
They probably want the information public IMO

**Comment by sydneyitguy** [comment]
Thanks for your suggestion, but we do need those information be called publicly.
