### ISSUE TITLE
Audit: Missing checks for address(0) when assigning values to address state variables

### ISSUE THREAD

**Issue by the-first-elder** [Steemhunt/mint.club-v2-contract#37]
Assigning values to address state variables without checking for address(0)

```
Found in MCV2_Royalty.sol: Line: 32

```

**Comment by sydneyitguy** [comment]
Your line reference is out of sync with the main branch:
https://github.com/Steemhunt/mint.club-v2-contract/blob/main/contracts/MCV2_Royalty.sol#L32

I'm not sure which line you're referring to.

**Comment by the-first-elder** [comment]
```javascript

 function updateProtocolBeneficiary(address protocolBeneficiary_) public onlyOwner {
        protocolBeneficiary = protocolBeneficiary_;
    }
```

check for Zero Address.. Had to make the project in Foundry hence my Source... Sorry about that

**Comment by sydneyitguy** [comment]
The function is an admin-only call and can be called again if any mistake is made, so I think adding validation to that is not necessary.
