### ISSUE TITLE
Audit:  Functions not used internally could be marked external

### ISSUE THREAD

**Issue by the-first-elder** [Steemhunt/mint.club-v2-contract#38]
```
Found in src/MCV1_Wrapper.sol: Line: 49
Found in src/MCV2_MultiToken.sol: Line: 42
Found in src/MCV2_MultiToken.sol: Line: 50
Found in src/MCV2_Token.sol: Line: 33
Found in src/MCV2_Token.sol: Line: 40
Found in src/lib/ERC1155Initializable.sol: Line: 34
Found in src/lib/ERC1155Initializable.sol: Line: 41
Found in src/lib/ERC1155Initializable.sol: Line: 58
Found in src/lib/ERC1155Initializable.sol: Line: 76
Found in src/lib/ERC1155Initializable.sol: Line: 96
Found in src/lib/ERC1155Initializable.sol: Line: 110
Found in src/lib/ERC1155Initializable.sol: Line: 121
Found in src/lib/ERC20Initializable.sol: Line: 33
Found in src/lib/ERC20Initializable.sol: Line: 41
Found in src/lib/ERC20Initializable.sol: Line: 58
Found in src/lib/ERC20Initializable.sol: Line: 65
Found in src/lib/ERC20Initializable.sol: Line: 72
Found in src/lib/ERC20Initializable.sol: Line: 84
Found in src/lib/ERC20Initializable.sol: Line: 107
Found in src/lib/ERC20Initializable.sol: Line: 129
Found in src/mock/TestToken.sol: Line: 14
```

**Comment by sydneyitguy** [comment]
Your line reference is out of sync with the main branch:
https://github.com/Steemhunt/mint.club-v2-contract/blob/main/contracts/MCV2_Royalty.sol#L32

I'm not sure which line you're referring to.

**Comment by the-first-elder** [comment]
Apparently looking at the repo now  some of the code had changed from the one on my local Machine,

Here are the ones that is left unchanged


https://github.com/Steemhunt/mint.club-v2-contract/blob/main/contracts/MCV1_Wrapper.sol#L74
https://github.com/Steemhunt/mint.club-v2-contract/blob/main/contracts/MCV2_MultiToken.sol#56
https://github.com/Steemhunt/mint.club-v2-contract/blob/main/contracts/MCV2_MultiToken.sol#56

**Comment by sydneyitguy** [comment]
- https://github.com/Steemhunt/mint.club-v2-contract/blob/main/contracts/MCV2_MultiToken.sol#L56
This function is already external

**Comment by sydneyitguy** [comment]
Fixed the one on `[MCV1_Wrapper.sol#L74](https://github.com/Steemhunt/mint.club-v2-contract/blob/main/contracts/MCV1_Wrapper.sol#L74)`
