### ISSUE TITLE
 A large lockUp length may result in reverts and extended transaction processing delays.

### ISSUE THREAD

**Issue by Tech-Icons** [Steemhunt/mint.club-v2-contract#40]
inside the locker.locker and sol::getLockUpIdsByReceiver.Sol::getLockUpIdsByToken, a large lockUp length may result in reverts and extended transaction processing delays.

consequence-
the use of an array in the locker to store user information.sol::createLockUp could lead to an overly complex for loop that uses more computing power than is available. As a result, transactions could experience reversals and delays. The larger the lockupLength, the more serious this problem is.

**Comment by Tech-Icons** [comment]
![view](https://github.com/Steemhunt/mint.club-v2-contract/assets/123077342/6736a8cd-bfc7-4e61-8633-a26c57003056)
prove of script

Recommendation-
It is recommended to investigate less dependant on for loop iterations and more gas-efficient alternatives for storing user lockup data. This can lessen the chance of reverts and minimize any transaction delays.

0x7F60eCB087eF0b852C19d5248b57e472F7066B5C

**Comment by sydneyitguy** [comment]
Duplicates with:
- https://github.com/Steemhunt/mint.club-v2-contract/issues/32
- https://github.com/Steemhunt/mint.club-v2-contract/issues/21
