### ISSUE TITLE
Lack of event emissions in MCV2_Token.sol

### ISSUE THREAD

**Issue by sirius651** [Steemhunt/mint.club-v2-contract#44]
https://github.com/Steemhunt/mint.club-v2-contract/blob/main/contracts/MCV2_Token.sol#L44

```
function mintByBond(address to, uint256 amount) external onlyBond {
        _mint(to, amount);
    }

    /**
     * @dev Burns tokens by the bonding curve contract.
     * Burning tokens affects the bonding curve.
     * Users can simply send tokens to the token contract address for the same burning effect without changing the totalSupply.
     * @param account The address from which the tokens will be burned.
     * @param amount The amount of tokens to burn.
     */
    function burnByBond(address account, uint256 amount) external onlyBond {
        _spendAllowance(account, bond, amount); // `msg.sender` is always `bond`
        _burn(account, amount);
    }
```

This contract also does not emit custom events for minting or burning. Consider adding events to provide transparency and enable tracking of these actions on-chain?

**Comment by sydneyitguy** [comment]
I think the _mint and _burn functions will emit a Transfer event from the token implementation already, so having another event emission is unnecessary?

**Comment by weed0607** [comment]
sorry but where can I find the `MCV2_ICommonToken` exact implementation?

**Comment by sydneyitguy** [comment]
@weed0607 They're on:
- https://github.com/Steemhunt/mint.club-v2-contract/blob/main/contracts/lib/ERC20Initializable.sol
- https://github.com/Steemhunt/mint.club-v2-contract/blob/main/contracts/lib/ERC1155Initializable.sol

**Comment by sydneyitguy** [comment]
Also, those `mintByBond`/`burnByBond` functions can only be called on the Bond contract, and it emits Mint/Burn events there too: 
https://github.com/Steemhunt/mint.club-v2-contract/blob/main/contracts/MCV2_Bond.sol#L404
