### ISSUE TITLE
Audit: Bypassing royalty fees using precision loss

### ISSUE THREAD

**Issue by 0x3agle** [Steemhunt/mint.club-v2-contract#48]
### Severity
High

### Description
- Users can mint and burn their tokens. Whenever this happens, a royalty is deducted to fund the protocol and the bond creator.
- This royalty is calculated using the following function
```solidity
  function getRoyalty(uint256 reserveAmount, uint16 royaltyRatio) internal pure returns (uint256) {
        return reserveAmount * royaltyRatio / RATIO_BASE;
    }
```
- A malicious user can provide a mint amount due to which (reserve amount * royalty ratio) yields a smaller value than RATIO_BASE, the royalty will be rounded down to zero, bypassing it.
- This further compounds when the protocol cut is calculated:
```solidity
 function addRoyalty(address beneficiary, address reserveToken, uint256 royaltyAmount) internal {
        uint256 protocolCut = royaltyAmount * PROTOCOL_CUT / RATIO_BASE;
        userTokenRoyaltyBalance[beneficiary][reserveToken] += royaltyAmount - protocolCut;
        userTokenRoyaltyBalance[protocolBeneficiary][reserveToken] += protocolCut;
    }
```

**Comment by 0x3agle** [comment]
A simple mitigation could be checking if the `return value != 0` and if it is, revert with a custom error `MintAmountTooSmall`

**Comment by sydneyitguy** [comment]
This is an intended behavior and has been tested on:
https://github.com/Steemhunt/mint.club-v2-contract/blob/main/test/Bond.test.js#L756
