### ISSUE TITLE
Decimals in ERC20 tokens can differ across chains.

### ISSUE THREAD

**Issue by weed0607** [Steemhunt/mint.club-v2-contract#52]
Decimals in ERC20 tokens can differ across chains.
And in the `MCV2_Bond.sol` the `reserveToBond` or `reserveFromBond` are calculated according to the tokens decimal.
```solidity
reserveToBond += Math.ceilDiv(supplyLeft * steps[i].price, multiFactor);
```
[[363](https://github.com/Steemhunt/mint.club-v2-contract/blob/25ed1971e8792e97daf9f4c5ed123385ffa24b00/contracts/MCV2_Bond.sol#L363C45-L363C45)]
```solidity
reserveFromBond += ((tokensToProcess * steps[i].price) / multiFactor);
````
[[438](https://github.com/Steemhunt/mint.club-v2-contract/blob/25ed1971e8792e97daf9f4c5ed123385ffa24b00/contracts/MCV2_Bond.sol#L438C25-L438C25)]

And this will be a problem to the accounting. Ensure consistent ERC20 decimals or implement chain-specific adjustments.

**Comment by sydneyitguy** [comment]
Not only on different chains but also every ERC20 token has different decimals, so we use the `multiFactor` variable from the token's decimal.

```solidity
uint256 multiFactor = 10**t.decimals();
...
reserveToBond += Math.ceilDiv(supplyLeft * steps[i].price, multiFactor);
```

Is there any issue with this?

**Comment by weed0607** [comment]
Different tokens using different decimals is ok for the accounting, I think, since the accounting is depend on the token. Different decimals of different tokens will not affect each other.
But on different chain, if the decimal changes the reserveToBond will be different due to the different system.
So on different chain, users will get different output.
That is what I am talking about.

**Comment by sydneyitguy** [comment]
Do you mean that the same token, for example, USDT, may have different decimals on Polygon and Ethereum, and that may cause an issue?

The contract doesn't communicate cross-chain, so all bond reserve is bound to a specific token and a specific chain. So even though the same token has different decimals on a different chain, that may not cause any issue with the bond reserve. 

Am I understanding it correctly?

**Comment by weed0607** [comment]
Correct

**Comment by sydneyitguy** [comment]
>The contract doesn't communicate cross-chain, so all bond reserve is bound to a specific token and a specific chain. So even though the same token has different decimals on a different chain, that may not cause any issue with the bond reserve. 

Then what's the issue?

**Comment by weed0607** [comment]
No, I misunderstood, sorry
