### ISSUE TITLE
Suggestions for limiting to EOA for a fair open airdrop

### ISSUE THREAD

**Issue by alsldl** [Steemhunt/mint.club-v2-contract#54]
If you want open airdrops (similar use case scenario with BRC20) which you told at [issue#33](https://github.com/Steemhunt/mint.club-v2-contract/issues/33),  I think you need to check if it's an EOA or not.

If you don't, greedy users can get every token allowed at distribution.
For example, a greedy user can deploy a new contract using a command like `create2` and then receives tokens from it.

When accessed through a contract created with `create2`, the `msg.sender` will continue to change, so the user can continue to receive distributions unconstrained by `isClaimed`, there's nothing to stop the user.

If you not intend it, you should check they are EOA or not.

Like below:
```solidity
if(tx.origin != msg.sender) revert("Distribution should be fair");
```
It blocks all smart contract's access.

**Comment by Tech-Icons** [comment]
I believe airdrop should be fair to everyone, especially on Bitcoin ETF

**Comment by sydneyitguy** [comment]
@alsldl Valid point! `tx.origin` is not a perfect way to prevent contract interaction, but probably a good filter!

**Comment by 0x3agle** [comment]
If this filter is applied, users using ERC4337-based wallets won't be able to claim their airdrop.

**Comment by sydneyitguy** [comment]
@0x3agle, hmm... that is also true. We'll discuss this issue in the team and see.

**Comment by sydneyitguy** [comment]
Okay, we've added this check for public airdrop cases to prevent abuse. This won't completely eliminate bot claiming but will make it more challenging. 
As @0x3agle mentioned, ERC4337-based wallets will also be unable to claim; however, they can use an EOA to do so.

**Comment by ddimitrov22** [comment]
@sydneyitguy I don't believe this is a proper solution as this will not allow multi-sigs and ERC4337 wallets to interact with the protocol which is against the nature of the web3. I believe setting a proper `merkleRoot` will be much more appropriate and effective against spamming new contracts with `create2` and will not limit the users of the protocol to only EOAs.

**Comment by sydneyitguy** [comment]
@ddimitrov22 This issue pertains exclusively to public airdrop cases. If a creator wishes to fully protect their project while allowing contract-based wallets, they can opt to add a `merkleRoot`, thus making the airdrop whitelist-only. This fix doesn't restrict whitelist-only airdrops from contract wallets. The limitation applies solely to public airdrop scenarios.

https://github.com/Steemhunt/mint.club-v2-contract/commit/42988c8644d1eb69b5096024797700b8e3c96f9c#diff-357b5afa1056aacdc3c0de2c2b9de8962f5ad020324fc9b54f624a3de727cb92R141-R145

As you can see here, the condition only applies under 
```
if (distribution.merkleRoot == bytes32(0)) { // Public airdrop
```
case
