### ISSUE TITLE
Initializers can be front-run

### ISSUE THREAD

**Issue by weed0607** [Steemhunt/mint.club-v2-contract#55]
Initializers could be front-run, allowing an attacker to either set their own values, take ownership of the contract, and in the best case forcing a re-deployment.
There are two instances of these problems
```solidity
File: contract/MCV2_Token.sol
23: function init(string calldata name_, string calldata symbol_) external {

File: contract/MCV2_MultiToken.sol
37: function init(string calldata name_, string calldata symbol_, string calldata uri_) external {
````

**Comment by 0x3agle** [comment]
- That would have been true if the `deployment` and `initialization` happed in two separate transactions.
- In here, both are happening in a single transaction:

```solidity
MCV2_Token newToken = MCV2_Token(token); //deployment 
newToken.init(tp.name, tp.symbol); //initialization 
```
- Hence, this scenario is not possible.

**Comment by sydneyitguy** [comment]
I agree to @0x3agle

**Comment by weed0607** [comment]
I only checked the deployment test.
In the test, there was not immediate initialization.
Sorry, I think this one is invalid one, again
