### ISSUE TITLE
Favor pull over push for external calls

### ISSUE THREAD

**Issue by 0x3agle** [Steemhunt/mint.club-v2-contract#56]
> "External calls can fail accidentally or deliberately, which can cause a DoS condition in the contract. To minimize the damage caused by such failures, it is better to isolate each external call into its own transaction that can be initiated by the recipient of the call. This is especially relevant for payments, where it is better to let users withdraw funds rather than push funds to them automatically (this also reduces the chance of problems with the gas limit)."

Ref: https://consensys.github.io/smart-contract-best-practices/development-recommendations/general/external-calls/#favor-pull-over-push-for-external-calls

Current Implementation:
```solidity
    function _collectCreationFee(uint256 amount) internal {
        if (amount != creationFee) revert MCV2_Royalty__InvalidCreationFee();
        if (creationFee == 0) return;

        (bool success, ) = payable(protocolBeneficiary).call{value: amount}("");
        if (!success) revert MCV2_Royalty__CreationFeeTransactionFailed();
    }
```

Recommend to update it to:
```solidity
    uint256 public creationFeeCollected;

    function _collectCreationFee(uint256 amount) internal {
        if (amount != creationFee) revert MCV2_Royalty__InvalidCreationFee();
        if (creationFee == 0) return;

        creationFeeCollected += amount;
    }

    function claimCreationFee() external {
        require (_msgSender() == protocolBeneficiary);
        uint fee = creationFeeCollected;
        creationFeeCollected = 0;

        (bool success, ) = payable(protocolBeneficiary).call{value: fee}("");
        if (!success) revert();
    }
    
```

**Comment by ddimitrov22** [comment]
This is usually a best practice. However, here the recipient is `protocolBeneficiary` which is expected to be trusted and controlled by the protocol.

**Comment by 0x3agle** [comment]
Yeah, that's why I don't see any harm in following it. 
Hence, "best practice", plus it saves gas.

**Comment by sydneyitguy** [comment]
@0x3agle Thanks for your suggestion! This is a valid point, but I would just keep our current implementation for the following reasons:
1. Like @ddimitrov22 mentioned, the recipient is protocolBeneficiary, which is expected to be trusted and controlled by the protocol.
2. Sending the balance to the beneficiary address directly is more convenient for accounting.
3. From my test, it costs about 3800 gas for sending ETH, but storing creationFeeCollected adds about 7400 gas, which is more expensive.
