### ISSUE TITLE
A vicious token can lead to user loss of funds

### ISSUE THREAD

**Issue by Francis510** [Steemhunt/mint.club-v2-contract#61]
A vicious token can lead to user loss of funds review your code

**Comment by Cathediral2018** [comment]
@Francis510 can you show us the code and point out where you think there is error so the team can review .
Thanks

**Comment by sydneyitguy** [comment]
You mean having base assets as vicious tokens with features like rebasing or tax functionalities?
Ref:
- https://github.com/Steemhunt/mint.club-v2-contract?tab=readme-ov-file#custom-erc20-tokens-as-reserve-tokens
- https://github.com/Steemhunt/mint.club-v2-contract/blob/main/test/Bond.test.js#L818

**Comment by Francis510** [comment]
Sure, here's the corrected code snippet with some additional comments for clarity:

function _setBond(BondParams memory bp, Token token) internal {
    require(bp.stepRanges.length == bp.stepPrices.length, "Step ranges and prices arrays must have the same length");

    for (uint i = 0; i < bp.stepRanges.length; i++) {
        // Check if the product of step range and step price is greater than or equal to 10^token.decimals()
        if (bp.stepRanges[i] * bp.stepPrices[i] >= 10 ** token.decimals()) {
            revert("Product of step range and step price exceeds threshold");
        }
    }
    // Other logic for setting bonding parameters
}


In this corrected code snippet, I added a comment to explain the purpose of the check and also improved the error message for the revert statement to provide more context. Additionally, I added a require statement to check that the lengths of stepRanges and stepPrices arrays are the same before iterating over them.

**Comment by Francis510** [comment]
> @Francis510 can you show us the code and point out where you think there is error so the team can review . Thanks

**Comment by Cathediral2018** [comment]
@sydneyitguy i think @Francis510 might be on to something her

**Comment by sydneyitguy** [comment]
@Francis510 Did you copy your comment from https://github.com/Steemhunt/mint.club-v2-contract/issues/58 ? 
I don't think your comment makes sense in this thread. Closing this thread as invalid.
