### ISSUE TITLE
Audit: Remove Magic Numbers

### ISSUE THREAD

**Issue by the-first-elder** [Steemhunt/mint.club-v2-contract#62]
Prevent Magic Numbers. Numbers should be Defined as Constants.

https://github.com/Steemhunt/mint.club-v2-contract/blob/801f94708aad9871e0deea7c95b94a39d555c50d/contracts/MCV2_Bond.sol#L168

https://github.com/Steemhunt/mint.club-v2-contract/blob/801f94708aad9871e0deea7c95b94a39d555c50d/contracts/MCV2_Bond.sol#L169

https://github.com/Steemhunt/mint.club-v2-contract/blob/801f94708aad9871e0deea7c95b94a39d555c50d/contracts/MCV2_Bond.sol#L170

**Comment by sydneyitguy** [comment]
Valid point!
