### ISSUE TITLE
Audit: Protocol Should Consider deployment With solidity 0.8.18 instead

### ISSUE THREAD

**Issue by the-first-elder** [Steemhunt/mint.club-v2-contract#63]
Description.

`solc` frequently releases new compiler versions. Using an old version prevents access to new Solidity security checks. We also recommend avoiding complex pragma statement.
Recommendation

Deploy with any of the following Solidity versions:

    0.8.18

The recommendations take into account:

    Risks related to recent releases
    Risks of complex code generation changes
    Risks of new language features
    Risks of known bugs

[Information above can Be found here](https://github.com/crytic/slither/wiki/Detector-Documentation#recommendation-79)

**Comment by Tech-Icons** [comment]
vote for this

**Comment by sydneyitguy** [comment]
I guess this is a duplicate of: https://github.com/Steemhunt/mint.club-v2-contract/issues/29
I'm considering downgrading to `0.8.19`, but it's not easy as we use many features OpenZeppelin 5.0 provides (which also uses `0.8.20`), especially custom errors.
