### ISSUE TITLE
Adding about part of this repo

### ISSUE THREAD

**Issue by web3isthefuture** [Steemhunt/mint.club-v2-contract#67]
### Summary:
I'd like to suggest adding an 'About' section to the Mint Club V2 repository page. This section could provide visitors with a quick overview of the project, its purpose, and its key features.

### Description:
As a frequent visitor to various GitHub repositories (and even now is during community audit period for mint club v2), I've found that an 'About' section significantly enhances the initial understanding of a project. For Mint Club V2, this could be particularly beneficial, given the project's innovative approach to token creation and management.

**Proposed 'About' Section Content:**
- **Project Overview**: A brief introduction to Mint Club V2, highlighting its role as an advanced token creator utilizing a bonding curve for generating new tokens.
- **Key Features**: A list of the main features and innovations of Mint Club V2, such as its use of base tokens as collateral and its discrete bonding curve mechanism.
- **Goals and Objectives**: A concise outline of what Mint Club V2 aims to achieve in the DeFi space.
- **Link to Documentation**: A direct link to the detailed documentation or Wiki for users who wish to dive deeper into the technical aspects.

### Benefits:
- **Enhanced Clarity**: New visitors will immediately understand the purpose and scope of the project.
- **Increased Engagement**: An informative 'About' section can increase dev engagement and interest, including community audit.
- **Better Navigation**: Users can quickly find essential links and information about the project.

I believe this addition will greatly benefit the Mint Club V2 community and first-time visitors to the repository. Thank you for considering this suggestion!

Kind regards,
@web3isthefuture

**Comment by sydneyitguy** [comment]
@cyh76507707 Please check this update in README:
https://github.com/Steemhunt/mint.club-v2-contract/commit/0729b571dc43c426ffcc84d0afdfa3344b9f8dc3

**Comment by cyh76507707** [comment]
We can add the demo video too - https://www.youtube.com/watch?v=BR_MJozU-DU

**Comment by cyh76507707** [comment]
1. **Token Creation (ERC20 or ERC1155)**
   * Create a bonding curve token (ERC20) or NFT (ERC1155) by using another ERC20 token as the base asset for your token's bonding curve pool.
   * Choose from curve types such as linear, exponential, or flat line, and adjust the price variation intervals for your token's journey.
   * Set key token specifications like starting price, free minting allocation, maximum price, and supply.
   * Deploy your asset on various Layer 1 and 2 networks.

2. **Buy (= Mint) and Sell (= Burn) Bonding Curve Asset**
   * When a bonding curve token is bought, the price curve determines the amount of the base token to be paid, enabling a swap. The paid base tokens are stored in the bonding curve pool, and an equivalent amount of the bonding curve tokens is minted to the buyer.
   * Conversely, when a bonding curve token is sold, the curve calculates the amount of base tokens to be returned. These base tokens are then returned to the seller, and the equivalent bonding curve tokens are burned.

3. **Airdrop Tool**
   * Set up a public or private airdrop for ERC20 or ERC1155 tokens created on Mint Club V2.
   * For private airdrops, Mint Club offers a merkleRoot-based whitelist feature.

4. **Lock-up Tool**
   * Create a contract-bound lock-up schedule for ERC20 or ERC1155 tokens created on Mint Club V2.
   * Specify the unlock time and recipient address for after the lock-up period is completed.

**Comment by sydneyitguy** [comment]
@web3isthefuture What do you think about the updates?

**Comment by web3isthefuture** [comment]
Oh wow the vid is the exact thing that I wanted! Good to make mint club v2 repo not only community-audited but also community-friendly :)

**Comment by web3isthefuture** [comment]
Explanation is also clear :D
